version: "3.7"

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - 3000:3000
    volumes:
      - "logs-dir:/usr/app/logs:rw"

  elk:
    build: 
      context: ./docker-services/elk
      dockerfile: Dockerfile
    container_name: translation-log-elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    volumes: 
      - "logs-dir:/usr/translation/logs:ro"
    depends_on: 
      - app

volumes: 
  logs-dir: